### ISSUE TITLE
Add privacy and code of conduct

### ISSUE THREAD

**Issue by katjam** [CodeReadingClubs/www#20]
For inspiration maybe look at:

https://joyofcoding.org/2016/code-of-conduct.html
http://bangbangcon.com/conduct.html

https://github.com/CodeReadingClubs/www/tree/policies

**Comment by danfishgold** [comment]
Added some stuff in #22

**Comment by katjam** [comment]
@katjam looking at "How to be with each other":

![image](https://user-images.githubusercontent.com/861172/119366696-215a6800-bca9-11eb-99c2-6466197c7beb.png)

**Comment by katjam** [comment]
Closed by #26 - though we might want to update - this is very much first draft
